# Generated by Django 5.2.17 on 2026-09-03 08:16

import django.db.models.deletion
import residentdb.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoveIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(db_index=True, max_length=8)),
                ('trigger_message_id', models.CharField(max_length=512, unique=True)),
                ('trigger_subject', models.TextField(blank=True)),
                ('trigger_sender', models.CharField(blank=True, max_length=320)),
                ('trigger_received', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('needs_outreach', 'Needs outreach'), ('handled', 'Already handled by a colleague'), ('unclear', 'Could not be read'), ('staged', 'Prepared, waiting for confirmation'), ('completed', 'Confirmed and actioned')], db_index=True, default='needs_outreach', max_length=32)),
                ('evidence_kind', models.CharField(blank=True, max_length=32)),
                ('evidence_detail', models.TextField(blank=True)),
                ('problems', models.TextField(blank=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-trigger_received', 'unit'],
                'indexes': [models.Index(fields=['status', 'unit'], name='residentdb__status_1b8513_idx')],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('welcome_draft', 'Welcome email draft'), ('internet_portal', 'Internet provider entry'), ('resident_app', 'Resident app entry')], max_length=32)),
                ('outcome', models.CharField(choices=[('staged', 'Staged, awaiting confirmation'), ('approved', 'Approved and carried out'), ('rejected', 'Rejected by the operator'), ('failed', 'Attempted and failed')], db_index=True, default='staged', max_length=32)),
                ('summary', models.TextField(blank=True)),
                ('blocked_on', models.TextField(blank=True)),
                ('staged_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('move_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='residentdb.movein')),
            ],
            options={
                'ordering': ['-staged_at'],
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', residentdb.fields.EncryptedTextField(blank=True)),
                ('last_name', residentdb.fields.EncryptedTextField(blank=True)),
                ('email', residentdb.fields.EncryptedTextField(blank=True)),
                ('phone', residentdb.fields.EncryptedTextField(blank=True)),
                ('date_of_birth', residentdb.fields.EncryptedTextField(blank=True)),
                ('unit', models.CharField(db_index=True, max_length=8)),
                ('lease_start', models.CharField(blank=True, max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('move_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='residentdb.movein')),
            ],
            options={
                'ordering': ['unit', 'id'],
            },
        ),
    ]
